### PR TITLE
Bring motion closer to the real thing

### PR DESCRIPTION
**Pull request by naoyuki2110**
# Description

Make motions in Windows11 more realistic by improving the `transition` property.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by yashash1511** [comment]
the looks like now it comes in fast & goes out slow but in real it looks the opposite

**Comment by yashash1511** [comment]
for the start menu when switching between stmenu and allCont 0.6sec is too much

**Comment by yashash1511** [comment]
image
image
image
image

duplication

**Comment by yashash1511** [comment]
for the startmenu when switching between all-apps and the startmenu

opacity will transition in 100ms the let it transform translate in 200ms it will be a more realistic effect

**Comment by yashash1511** [comment]
@naoyuki2110  the calendar pane looks like now it comes in fast & goes out slow but in real it looks the opposite

**Review by yashash1511 — APPROVED** [review]
lgtm

**Review by yashash1511 — COMMENTED** [review]
regarding the action center and calendar I think it was fine before.

in the start menu this one looks better

**Comment by yashash1511** [comment]
I will do some required changes and merge

**Comment by yashash1511** [comment]
thank you

**Comment by blueedgetechno** [comment]
Good job, guys

**Pull request merged**
