### PR TITLE
fix : backdrop blur outside the widgetsPane

### PR DESCRIPTION
**Pull request by yashash1511**
image
befor

image
after

### CODE REVIEW

**Comment by yashash1511** [comment]
: )

**Comment by cupofcoffebruh** [comment]
👀

**Comment by yashash1511** [comment]
> image befor
> 
> image after

feel free to use these imgs in spot the difference like games ;)

**Comment by blueedgetechno** [comment]
I fail to notice this issue, what browse are you using?

image
(source: dev.blueedge.me)

**Comment by yashash1511** [comment]
@blueedgetechno I am using Edge 

I can see it in the image you sent also (though not as   much) , I am using a color accurate,calibrated monitor)

Screenshot_20211110-093057_Chrome_1 this is cropped from the image u sent only

The blur is there outside the widgets pane (much more noticeable in the image in the first comment)

**Comment by yashash1511** [comment]
image
src(dev.blueedge.me)

**Comment by blueedgetechno** [comment]
ok cool

**Comment by blueedgetechno** [comment]
tuta phuta code, aaye na kisi ke kaam,
chalo kare ye pull request merge
leke prabhu ka naam

**Comment by yashash1511** [comment]
> tuta phuta code, aaye na kisi ke kaam, chalo kare ye pull request merge leke prabhu ka naam

xD

**Pull request merged**
