### PR TITLE
I have updated SECURITY.md

### PR DESCRIPTION
**Pull request by VanshajPoonia**

### CODE REVIEW

**Comment by blueedgetechno** [comment]
I would rather prefer bugs and vulnerabilities being documented here rather unorganised on discord server.
And since it's a static web application, It's hard for any security vulnerability are rare and the common ones are mainly performance issue or bugs related to some action in the application.

**Comment by VanshajPoonia** [comment]
> I would rather prefer bugs and vulnerabilities being documented here rather unorganised on discord server. And since it's a static web application, It's hard for any security vulnerability are rare and the common ones are mainly performance issue or bugs related to some action in the application.

Ohk, will try to find bugs and fix them in the future.

**Comment by blueedgetechno** [comment]
No I mean you wrote, "If you find a security vulnerability in the Win11react project, kindly send a message to any of the **SUPER MODS** on the Discord Server instead of posting a public issue in GitHub."

That should be changed to something generic.

**Comment by VanshajPoonia** [comment]
> No I mean you wrote, "If you find a security vulnerability in the Win11react project, kindly send a message to any of the **SUPER MODS** on the Discord Server instead of posting a public issue in GitHub."
> 
> That should be changed to something generic.

Sorry but can't understand what you want to say :( I mean what do you mean by generic here?

**Comment by VanshajPoonia** [comment]
Actually, I wrote so because that happens in most of the Open-source projects. They ask the contributors to report the bug to them on email or stuff and not publically. So that's why I wrote so.

**Comment by blueedgetechno** [comment]
Something as simple as "Check if your issue exist before creating another" and some more in an ordered fashion. It really doesn't matter as long as the message is right.

**Comment by VanshajPoonia** [comment]
> 

Oh Ok! got it now

**Comment by VanshajPoonia** [comment]
> Something as simple as "Check if your issue exist before creating another" and some more in an ordered fashion. It really doesn't matter as long as the message is right.

Can you please merge it now? I wanna be a part of the community!!

**Comment by yashash1511** [comment]
image
vro in 7th line (discuss something) ig it shouldn't be under the 'Reporting vulnerablity' subHeading

**Comment by blueedgetechno** [comment]
gg

**Pull request merged**
