### PR TITLE
deploy preview checker

### PR DESCRIPTION
**Pull request by yashash1511**
# DO NOT MERGE

just to check if the PR preview works because lukas won't let me test on his PR

### CODE REVIEW

**Comment by yashash1511** [comment]
10sec reduced (build time for jakejarvis/wait-action)

**Comment by Lukas-Batema** [comment]
Lol @yashash1511

**Comment by yashash1511** [comment]
nic it now updates the comment when preview is ready

**Comment by yashash1511** [comment]
closing should remove the image folder

**Comment by Lukas-Batema** [comment]
Dew yue noe jaoe

**Comment by andrewstech** [comment]
E58FD730-1C23-40CD-8C24-DE7B022CB1F4

**Pull request closed without merging**
