### PR TITLE
add icons to more settings

### PR DESCRIPTION
**Pull request by shaunbharat**
# Description

This PR adds the correct icons to more of the setting items. Only a few more icons are still missing.

## Fixes # (issue)

This PR advances progress on issue #339.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by shaunbharat** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by shaunbharat — COMMENTED** [review]
I rechecked that the icons I added were the correct ones in the deploy (PR) preview.

**Review by yashash1511 — APPROVED** [review]
Thanks a lot @shaunbharat

**Review by yashash1511 — COMMENTED** [review]
lgtm

**Pull request merged**
