### PR TITLE
Test WiFi Status

### PR DESCRIPTION
**Pull request by Lukas-Batema**
# Description
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by yashash1511** [comment]
image
why though

**Comment by Lukas-Batema** [comment]
GitHub actions were undergoing maintenance

**Comment by andrewstech** [comment]
> GitHub actions were undergoing maintenance

Can fix this one sec

**Comment by yashash1511** [comment]
image
nic

**Comment by yashash1511** [comment]
image

**Comment by Lukas-Batema** [comment]
Hey, it somewhat is working...

> image

**Comment by Lukas-Batema** [comment]
> image

It ain't ready yet... LMAO

**Comment by Lukas-Batema** [comment]
> image nic

nice*

**Comment by andrewstech** [comment]
> > image nic
> 
> nice*

https://i.kym-cdn.com/photos/images/newsfeed/000/759/181/cc1.gif

**Comment by andrewstech** [comment]
> > image nic
> 
> nice*

cc1

**Comment by yashash1511** [comment]
sup

**Comment by yashash1511** [comment]
Closing & reopening for new deploy preview

**Comment by Lukas-Batema** [comment]
> Closing & reopening for new deploy preview

But why? I haven't done anything since the last deployment...

**Comment by yashash1511** [comment]
> But why? I haven't done anything since the last deployment...

i made some updates to the deploy preview system to make it faster. new preview just to check that everything works fine

**Comment by Lukas-Batema** [comment]
> > But why? I haven't done anything since the last deployment...
> 
> i made some updates to the deploy preview system to make it faster. new preview just to check that everything works fine

You better stop, no.

**Comment by yashash1511** [comment]
> You better stop, no.

what why the update makes it faster

**Comment by yashash1511** [comment]
don't worry won't have to do this again
image

**Comment by yashash1511** [comment]
stale @Lukas-Batema

**Comment by Lukas-Batema** [comment]
> stale @Lukas-Batema

urmum stale

**Comment by Lukas-Batema** [comment]
Will work on this later

**Comment by andrewstech** [comment]
> stale @Lukas-Batema

Exams

**Pull request closed without merging**
