### PR TITLE
Start-up audio

### LINKED ISSUE #224: Windows 11 startup sound
**Is your feature request related to a problem? Please describe.**
I feel like adding a startup sound would make it feel more like Windows 11.
https://user-images.githubusercontent.com/77000356/143772836-6ff7a63b-953f-40f1-bf70-18d9b465ebd2.mp4

**Describe the solution you'd like**
. To play the sound upon startup of clone. 
**Describe alternatives you've considered**
None, other than completely omitting it. 
**Additional context**

### PR DESCRIPTION
**Pull request by andrewstech**
# Description
Adds startup audio

Fixes #224 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by andrewstech** [comment]
https://developer.chrome.com/blog/autoplay/

**Comment by yashash1511** [comment]
according to the documentation we can't autoplay until and unless there is something like atleast a click

image

users have to click here at the lock screen so we can do onclick here it should work ig
document.getElementById("startupAudio").play();

**Comment by blueedgetechno** [comment]
That is the thing, the Lock screen is designed to be activated on first visit so that user doesn't have to bother about it everytime.

Plus one can also lock the screen by going to start menu > lock

**Comment by yashash1511** [comment]
so we need to play it at the [bootscreen](https://github.com/blueedgetechno/win11React/blob/master/src/containers/background/index.js)

**Comment by bradygavinmeyer123** [comment]
it done

**Pull request closed without merging**
