### PR TITLE
react v18 & redux v8

### PR DESCRIPTION
**Pull request by yashash1511**

### CODE REVIEW

**Comment by andrewstech** [comment]
I see the issue one sec

**Comment by yashash1511** [comment]
> I see the issue one sec

image
it didn't fail this time

**Comment by andrewstech** [comment]
> > I see the issue one sec
> 
> image
> 
> it didn't fail this time

Its because the testing repo was pushing multiple commits at the same time. 20 previews were just generated

**Comment by yashash1511** [comment]
> Its because the testing repo was pushing multiple commits at the same time. 20 previews were just generated

ohhk

**Review by andrewstech — APPROVED** [review]
Merge when ready

**Comment by yashash1511** [comment]
gtg

**Pull request merged**
