### PR TITLE
Fixed typo in readme.md

### PR DESCRIPTION
**Pull request by MalikIdreesHasanKhan**
Why do I keep spotting typos?

### CODE REVIEW

**Comment by MalikIdreesHasanKhan** [comment]
Understandable, I am from India myself :)

**Comment by blueedgetechno** [comment]
The hell, I didn't write that in Readme 😤. It was you @andrewstech . I have a pretty strong english and winning certificate of a english high school debate to prove it. XD

**Comment by Lukas-Batema** [comment]
> The hell, I didn't write that in Readme 😤. It was you @andrewstech . I have a pretty strong english and winning certificate of a english high school debate to prove it. XD

Lmfao, @andrewstech, nice try. I guess I should've looked a bit harder for typos in #171.

**Comment by MalikIdreesHasanKhan** [comment]
@Lukas-Batema While I did find this by chance, there is a great python package called codespell, which finds typos in your code, get it here https://github.com/codespell-project/codespell

**Pull request merged**
