### PR TITLE
Settings App :(

### PR DESCRIPTION
**Pull request by yashash1511**
# The settings app has been added !!!

| image | image |
|-|-|

#53 #100 #302 #303 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

@blueedgetechno can you help the height of .nav_bottom & .tilesCont needs to be fixed

### CODE REVIEW

**Comment by yashash1511** [comment]
# DO NOT MERGE WIP

**Comment by blueedgetechno** [comment]
I have updated the code into the test branch, it should be live on https://dev.blueedge.me is few minutes, you can check that

**Comment by yashash1511** [comment]
> I have updated the code into the test branch, it should be live on https://dev.blueedge.me is few minutes, you can check that

thank uwu

**Comment by yashash1511** [comment]
https://user-images.githubusercontent.com/89068816/154526979-9a130220-af5c-4cb2-a653-45f1eb369a82.mp4


there were some bugs in the earlier implementation I will make the changes you did here and then it can be merged :)

**Comment by yashash1511** [comment]
> I have updated the code into the test branch, it should be live on https://dev.blueedge.me is few minutes, you can check that

thanks you

**Comment by yashash1511** [comment]
https://user-images.githubusercontent.com/89068816/154534941-324638ed-dd17-4f73-9b7f-d97e8a75aaa7.mp4

this bug happens on adding height:100% to .settingsApp .restWindow :(

**Comment by blueedgetechno** [comment]
Oh this bug is of container-query-polyfill, it doesn't updates the div elements on react state change. I will ry to fix it in the morning, if possible otherwise we would have to exlude that package.

**Comment by yashash1511** [comment]
> Oh this bug is of container-query-polyfill, it doesn't updates the div elements on react state change. I will ry to fix it in the morning, if possible otherwise we would have to exlude that package.

then how is it working rn in 314

**Comment by yashash1511** [comment]
@blueedgetechno for now I set a max-width to settings app ig we can make it more responsive for smaller screens later.

**Comment by yashash1511** [comment]
ok making new one againnnnnnn

**Comment by andrewstech** [comment]
It was due to the merge conflicts. If you close the pr the preview repo is then deleted. So closing then reopening with result in a failure.

**Comment by yashash1511** [comment]
ohhk got it

**Pull request closed without merging**
