### PR TITLE
Update

### PR DESCRIPTION
**Pull request by yashash1511**
restructuring few things
- .calnpane was in searchpane.scss instead of sidepane.scss
- seperate css file for widget
- obsolete code removed

|image|image|
|-|-|
|Before(Transparent & Blur)|After(solid color)|

Move to solid color instead of transparency & backdrop blur (actionCentre & calendarWidget) for better performance as well as looks :)

unknown
fixed

### CODE REVIEW

**Comment by blueedgetechno** [comment]
bruh, there is a force push.

**Comment by Lukas-Batema** [comment]
> bruh, there is a force push.

Ye

**Comment by yashash1511** [comment]
> bruh, there is a force push.

oops sorry :|

**Comment by Lukas-Batema** [comment]
Haha

**Review by Lukas-Batema — COMMENTED** [review]
No more force pushing @yashash1511, bad boy.

**Pull request merged**
