### PR TITLE
Fixed: Wi-Fi and Bluetooth toggling when flight mode is enabled.

### LINKED ISSUE #801: [Bug]: Clicking on Flight Mode
### What happened?

I have checked this when i clicked on the flight mode ,the wifi Sign is not replaced by the flight mode sign in the taskbar

### To reproduce the behavior?

We can create an event that trigger when we click on the flight mode and made that event change the wifi sign to taskbar sign  

### What browser are you seeing the problem on?

Chrome

### PR DESCRIPTION
**Pull request by git-init-priyanshu**
# Description

Now, when you enable Airplane mode, it will automatically disable Wi-Fi and Bluetooth if they were previously enabled.
Fixes #801 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by git-init-priyanshu** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by yashash-pugalia** [comment]
Can we toggle back Wifi when Flight mode is disabled.

**Comment by Saurabh-001-S** [comment]
Yess @yashash-pugalia I fix it in this [commit](https://github.com/blueedgetechno/win11React/pull/803)   but this work it not assign so it only commit not merged in main branches you can check it

**Comment by git-init-priyanshu** [comment]
> Can we toggle back Wifi when Flight mode is disabled.

When Wi-Fi is turned on and you activate flight mode, it automatically disables the Wi-Fi. If flight mode is still active, you have the option to re-enable the Wi-Fi (This feature is exists in Windows 11, so I kept it that way). And when you deactivate flight mode, you can once again enable the Wi-Fi.

Hope this clarifies things.

**Comment by yashash-pugalia** [comment]
> When Wi-Fi is turned on and you activate flight mode, it automatically disables the Wi-Fi. If flight mode is still active, you have the option to re-enable the Wi-Fi (This feature is exists in Windows 11, so I kept it that way). And when you deactivate flight mode, you can once again enable the Wi-Fi.

Thanks that makes sense.

**Pull request merged**
