### PR TITLE
darkMode - calculator :)

### PR DESCRIPTION
**Pull request by yashash1511**
image

okey? :)

### CODE REVIEW

**Review by MalikIdreesHasanKhan — COMMENTED** [review]
how do you turn dark mode on? I don't see any button in the calculator settings?

**Comment by yashash1511** [comment]
> how do you turn dark mode on? I don't see any button in the calculator settings?

there is not a button in calculator settings, u can turn it by turnning on dark mode in system :)

**Comment by blueedgetechno** [comment]
> You can turn it by turnning on dark mode in system :)
You mean my device?

**Comment by blueedgetechno** [comment]
and take care of those ToolBar button,

```<ToolBar app={wnapp.action} icon={wnapp.icon} name="Calculator" invert/>```

Notice the invert key, it sends a signal to use dark theme for toolbar. If you dont use it, it will render it with light theme.

**Comment by MalikIdreesHasanKhan** [comment]
Oh, get it. Thanks

**Comment by yashash1511** [comment]
> You mean my device? Does it detects and applies the dark theme?

yes sir it does, when you will turn dark mode in your pc the calc app will automatically go to dark mode too :)

**Review by MalikIdreesHasanKhan — APPROVED** [review]

**Comment by blueedgetechno** [comment]
> > You mean my device? Does it detects and applies the dark theme?
> 
> yes sir it does, when you will turn dark mode in your pc the calc app will automatically go to dark mode too :)

Ok for now, what we can do is make a dark mode toggle button in action center, maybe use that ```focus assist``` button.
Store that choice in local storage and render accordingly.

**Comment by blueedgetechno** [comment]
wait let me do it partially for ms-store, then you can see it

**Comment by yashash1511** [comment]
> wait let me do it partially for ms-store, then you can see it

yes that would be nice, you just do for one app I will get the approach and then I can implement for other apps as well :)

**Comment by MalikIdreesHasanKhan** [comment]
@blueedgetechno I think that is a better idea, because there are a few people who Don't use dark mode as the app mode, but the Windows theme.

**Comment by yashash1511** [comment]
> @blueedgetechno I think that is a better idea, because there are a few people who Don't use dark mode as the app mode, but the Windows theme.

what I implemented is exactly what all major sites use (eg. youtube, github ...) if device is in dark mode then the website by default also in dark mode ( though we can easily add a toggle to overide it usin [dark-mode-toggle](https://github.com/GoogleChromeLabs/dark-mode-toggle) )

**Comment by yashash1511** [comment]
> more tips: add a data-theme to the lets say `wnstore` class for ms-store and add dark theme css accordingly

I think instead of data-theme, media query (prefers-color-scheme) should be used as it respects users preference

**Comment by MalikIdreesHasanKhan** [comment]
@yashash1511  That is not what I meant to say. I meant that there should be a toggle as well because some people use light mode on windows but dark on GitHub.

**Comment by yashash1511** [comment]
> @yashash1511 That is not what I meant to say. I meant that there should be a toggle as well because some people use light mode on windows but dark on GitHub.

ik thats why I said 

> ( though we can easily add a toggle to overide it usin [dark-mode-toggle](https://github.com/GoogleChromeLabs/dark-mode-toggle) )

:)

**Comment by MalikIdreesHasanKhan** [comment]
Nice. When the settings app comes out, we can add a dark mode toggle in the settings as well.

**Comment by blueedgetechno** [comment]
It would be much better to just load initially the user preference in js and set the data-theme.

**Comment by MalikIdreesHasanKhan** [comment]
@blueedgetechno Agreed!

**Comment by yashash1511** [comment]
@blueedgetechno 

okey, so can you do dark mode for one app I will see it and then I can implement for other apps as well :)

**Comment by blueedgetechno** [comment]
ok, updating in 12 hours (hope so)

**Comment by blueedgetechno** [comment]
Ok have done it,
Check the applications/wnapp.scss file

These are some global css variables that will be required for quick text color change throughout the project
```css
body{
  --dark-txt: #000;
  --txt-col: #222;
   ....
}

body[data-theme="dark"]{
  --dark-txt: #fff;
  --txt-col: #ddd;
   ...
}
```
---

And for particular applications, do something like this
```css
.wnstore {
  --bg-color: #f3f3f3;
  --nav-btn-hov: #ffffff;
  ...
  --det-bg: #f9f9f9;
  background: var(--bg-color);
}

body[data-theme="dark"] .wnstore {
  --bg-color: #1c2126;
  --nav-btn-hov: #454545;
  ...
  --det-bg: #282C32;

  background: var(--bg-color);
}
```

I have taken care of toolbar (those minimize, maximize and close button or infact whole bar), you dont have to worry about it.

Try to use as much as global as you can, Make some global variables if its required. And try to use as minimum as per application css variables.

I might have used tailwind for quick text color for example ```text-gray-800```, you can remove that from js file and use any of the global css var.

**Comment by MalikIdreesHasanKhan** [comment]
@yashash1511 The calculator design looks great, but the real one is longer and sleeker as well as a little transparent.
This screenshot was taken on Windows 11 OS Build 22000.282.
reactvsreal

**Comment by MalikIdreesHasanKhan** [comment]
Light mode screenshot
but

**Comment by yashash1511** [comment]
> @yashash1511 The calculator design looks great, but the real one is longer and sleeker as well as a little transparent. This screenshot was taken on Windows 11 OS Build 22000.282. reactvsreal

bruhh update your calculator app thats win10 one

**Comment by MalikIdreesHasanKhan** [comment]
There should also be a transparent effect.

**Comment by yashash1511** [comment]
> There should also be a transparent effect.

transparency effect is there in light mode 
image
 but I didn't implemented it in dark mode cuz it doesn't look so good in it

**Comment by MalikIdreesHasanKhan** [comment]
Try it, I'm sure It may look good with a minimal amount.

**Comment by yashash1511** [comment]
> There should also be a transparent effect.

image

its not that it cant be implemented (I can do that very easily) but to acheive the above a lot more filters had to be used which ig will impact performance, hence I am refraining from implementing it :)

**Comment by MalikIdreesHasanKhan** [comment]
Understandable, have a great day!

**Comment by yashash1511** [comment]
> Ok have done it, Check the applications/wnapp.scss file

okey :)

**Comment by blueedgetechno** [comment]
> > There should also be a transparent effect.
> 
> image
> 
> its not that it cant be implemented (I can do that very easily) but to acheive the above a lot more filters had to be used which ig will impact performance, hence I am refraining from implementing it :)

very wise decision, performance first :)

**Comment by yashash1511** [comment]
I will make a new PR in test branch (cuz thats da one being used for dark mode ig) :)

**Pull request closed without merging**
