### PR TITLE
dark-mode : Notepad , update startMenu , "Sign in" button lockScreen , few fixes & changes

### PR DESCRIPTION
**Pull request by yashash1511**
image
image

### CODE REVIEW

**Comment by blueedgetechno** [comment]
image

- Battery issue
- Charger icon not getting dark

**Comment by yashash1511** [comment]
fixed Charger icon not getting dark

**Comment by MalikIdreesHasanKhan** [comment]
I was literally going to suggest a dark mode for notepad lol. Good job on the sign in button and notepad though :).

**Comment by blueedgetechno** [comment]
Is it ready for merging or do you want to add anything else?

**Comment by yashash1511** [comment]
> Is it ready for merging or do you want to add anything else?

it still shows * while charging :(

**Comment by blueedgetechno** [comment]
> > Is it ready for merging or do you want to add anything else?
> 
> it still shows * while charging :(

I will fix, it a simple bug when browser refuses to give batteryInfo.

**Pull request merged**
