### PR TITLE
andrews python attempt

### PR DESCRIPTION
**Pull request by andrewstech**

### CODE REVIEW

**Comment by andrewstech** [comment]
For anyone seeing this I have not slept in 24 hours.

**Comment by blueedgetechno** [comment]
> For anyone seeing this I have not slept in 24 hours.

Get some sleep, Right now !!

**Comment by Lukas-Batema** [comment]
> For anyone seeing this I have not slept in 24 hours.

RIP

**Comment by Lukas-Batema** [comment]
Ok, so a couple of weird issues:
- You cannot use `pip` or `python -m pip` (the former is a command not found, the latter is a blank white screen, because of the following issue)
- Using `python test`, `python -m`, or any python file/module execution, white-screens the page until reloading it

**Comment by MalikIdreesHasanKhan** [comment]
Weird

**Comment by Lukas-Batema** [comment]
Weird, with the `alert()` lines, they aren't showing up...

**Comment by Lukas-Batema** [comment]
> ❌ DEPLOY PREVIEW BUILD HAS FAILED

Figured

**Pull request closed without merging**
