### PR TITLE
dark-mode : finale :)

### PR DESCRIPTION
**Pull request by yashash1511**
# WIP DO NOT MERGE

|image|image| |
|-|-|-|
| about | widgets | browser (soon)|

### CODE REVIEW

**Comment by yashash1511** [comment]
okey : )

**Comment by yashash1511** [comment]
@andrewstech it is still Updating Deploy Preview on editing the first post :(

**Comment by blueedgetechno** [comment]
image

the text is not visible

**Comment by andrewstech** [comment]
> @andrewstech it is still Updating Deploy Preview on editing the first post :(

Will investigate

**Comment by blueedgetechno** [comment]
@yashash1511 can you pull the updates I made in test and add to this pull request before I merge it

**Comment by yashash1511** [comment]
> @yashash1511 can you pull the updates I made in test and add to this pull request before I merge it

done

**Pull request merged**
