### PR TITLE
settingsData.json proofreading edits

### LINKED ISSUE #605: [Bug]: Correct typographical errors and mistakes in grammar, style, and spelling in settingsData.json
### What happened?

Some of the entries inside settingsData.json have incorrect spelling - grammatical errors.

### To reproduce the behavior?

Open Settings and scroll through to find grammar/spelling errors.

### What browser are you seeing the problem on?

Chrome

### PR DESCRIPTION
**Pull request by imzivko**
# Description

Correct typographical errors and mistakes in grammar, style, and spelling in settingsData.json

Fixes #605 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by imzivko** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by imzivko** [comment]
recheck

**Comment by yashash1511** [comment]
please don't change Organisation, personalisation, optimisations to american english

**Comment by imzivko** [comment]
> 

resolved

**Comment by imzivko** [comment]
> please don't change words to american english (behaviours, Organisation, personalisation, optimisations)

resolved

**Comment by yashash1511** [comment]
> reacted

ig you missed behaviours

**Review by yashash1511 — APPROVED** [review]
LGTM

Thanks @imzivko

**Pull request merged**
