### PR TITLE
Small fix

### PR DESCRIPTION
**Pull request by cupofcoffebruh**
We don't use horizontal scrollbar

### CODE REVIEW

**Comment by yashash1511** [comment]
> We don't use horizontal scrollbar

should I add css for it?

**Comment by blueedgetechno** [comment]
people with no touchpad: 
image

**Comment by andrewstech** [comment]
avatars-000532708956-jsayvx-t240x240

My thoughts

**Comment by cupofcoffebruh** [comment]
@blueedgetechno the up and  down arrows are in the wrong place on the gallery scrollbar and  you can still navigate in the X-scrollbars with the left and right arrows  without touchpad
hide-the-pain-harold

**Comment by yashash1511** [comment]
image

aah I now see the bug will add css for horizontal scrollbar

**Comment by yashash1511** [comment]
image

ohh I now see the issue will fix :)

**Pull request closed without merging**
