### PR TITLE
new boot screen loader + fixes : )

### PR DESCRIPTION
**Pull request by yashash1511**
loader
new boot animation :)

### CODE REVIEW

**Comment by yashash1511** [comment]
image

**Comment by cupofcoffebruh** [comment]
👀

**Comment by blueedgetechno** [comment]
oh boy this is gonna cost some conflicts

**Comment by yashash1511** [comment]
> oh boy this is gonna cost some conflicts

kek

**Comment by yashash1511** [comment]
> oh boy this is gonna cost some conflicts

my 1st PR to this repo #131 already did that (It had changes worth one whole letter)

**Comment by blueedgetechno** [comment]
Yes I know, but I was working on file explorer too. But it's not a big deal, I can manage the conflicts.

**Comment by blueedgetechno** [comment]
funny, It didn't caused any conflicts.

**Pull request merged**
