### PR TITLE
Added Super Mario Bros as a game in the Microsoft store

### PR DESCRIPTION
**Pull request by MalikIdreesHasanKhan**
mariobros

### CODE REVIEW

**Comment by MalikIdreesHasanKhan** [comment]
Kindly DO-NOT_MERGE this, it's a WIP

**Comment by MalikIdreesHasanKhan** [comment]
Also I thought it would be better if Xbox was capitalised.

**Comment by blueedgetechno** [comment]
This is the default list of apps when the user fails to connect with store api hosted by this repo, https://github.com/win11bot/win11bot.

Add the game there not in this repo.

**Comment by blueedgetechno** [comment]
also the icon is not loadable, LOL

**Comment by blueedgetechno** [comment]
even more so, use this url https://supermario-game.com/mario-game/mario.html, its aleady in full screen

**Comment by MalikIdreesHasanKhan** [comment]
OK, will do it! Thanks @blueedgetechno

**Pull request closed without merging**
