### PR TITLE
dark-mode : Start & Search menu :)

### PR DESCRIPTION
**Pull request by yashash1511**
image

### CODE REVIEW

**Comment by yashash1511** [comment]
okey :)

**Comment by Posandu** [comment]
:O

**Comment by andrewstech** [comment]
👀

**Comment by yashash1511** [comment]
image

just saw this will fix

**Comment by blueedgetechno** [comment]
Is there any functional change in start.js or its just beautification?

**Comment by blueedgetechno** [comment]
and also this dark blue search bar looks dark in dark mode

image

**Comment by yashash1511** [comment]
> Is there any functional change in start.js or its just beautification?

no major changes just some changes in classNames (removed few tailwind classes that was something like txt-grey-900 ... ) I have set prettier to automatically run on saving file and hence you see the beautification

**Comment by yashash1511** [comment]
> and also this dark blue search bar looks dark in dark mode

ok will fix :)

**Pull request merged**
