### PR TITLE
Updated icons to match Windows 11 icons.

### PR DESCRIPTION
**Pull request by MalikIdreesHasanKhan**
The store, photos and phone icons have been updated.
store
yphone
photos

### CODE REVIEW

**Comment by yashash1511** [comment]
image

the newer icons dont look properly sized

**Comment by MalikIdreesHasanKhan** [comment]
Ok, will work on it.

**Comment by blueedgetechno** [comment]
kae sure they are 64x64 and perfectly fitted, dont change the code to fit it

**Comment by MalikIdreesHasanKhan** [comment]
@blueedgetechno  wasn't planning to change any code, this icon for ms store is 65x65.

**Comment by blueedgetechno** [comment]
yeah but they are padded and also dont change the about.js , it is Microsoft 365 Cloud pc

https://www.microsoft.com/en-us/windows-365

**Comment by MalikIdreesHasanKhan** [comment]
I am fixing the icons. I have already reverted the about.js file. (latest commit)

**Comment by blueedgetechno** [comment]
I have already changed the store icon in test branch in which ongoing dark mode is happening.

And for phone app, this is the logo currently I have installed and is on microsoft store too
image

**Comment by MalikIdreesHasanKhan** [comment]
Ok, will close the PR :)

**Pull request closed without merging**
