### PR TITLE
fix duplicate excel

### PR DESCRIPTION
**Pull request by yashash1511**
Excel was being shown twice because of it being added in the store

image
Thanks oliverGamez#8266 for bringing this issue to notice

### CODE REVIEW

**Comment by Lukas-Batema** [comment]
Good job :) I didn't have the time to fix this, so thank you!

**Comment by yashash1511** [comment]
> 

@andrewstech  maybe you could add a delay when this message commented

image

**Comment by Lukas-Batema** [comment]
> > ✔️ Deploy Preview for win11blue ready! 😎 Browse the preview: [241.pr.blueedge.me](https://241.pr.blueedge.me) ! 🔨 If you experience an SSL issue then wait 2 minutes and try again. 🔍 Inspect the deploy log: [blueedgetechno/win11React/actions/runs/1582650831](https://github.com/blueedgetechno/win11React/actions/runs/1582650831)
> 
> @andrewstech maybe a delay could be added before this message is commented
> 
> image

Still is happening for me, 4 mins later

**Comment by yashash1511** [comment]
@Lukas-Batema  same for me

**Comment by Lukas-Batema** [comment]
> `@Lukas-Batema` same for me
> 
> image maybe it could be due to this

Probably

**Comment by andrewstech** [comment]
The preview system seems to be having an issue with github pages.

**Comment by yashash1511** [comment]
> The preview system seems to be having an issue with github pages.

okey : )

**Comment by Posandu** [comment]
> @Lukas-Batema same for me
> 
> image maybe it could be due to this

@yashash1511 Hide email in the top right or prepare for spam attack!

**Comment by yashash1511** [comment]
> @yashash1511 Hide email in the top right or prepare for spam attack!

yes that happened

**Pull request merged**
