### PR TITLE
add ms- powerpoint 

### PR DESCRIPTION
**Pull request by ranvirsi**
i want PowerPoint in the windows11 in react

### CODE REVIEW

**Comment by blueedgetechno** [comment]
try making a pr to master branch so we can actually see your changes.

**Comment by andrewstech** [comment]
I cannot see any changes by you?

**Comment by andrewstech** [comment]
Yea its not even his repo its our master into our test branch

**Comment by Lukas-Batema** [comment]
> Yea its not even his repo its our master into our test branch

That's my point

**Pull request closed without merging**
