### PR TITLE
Add Settings app

### PR DESCRIPTION
**Pull request by yashash1511**
# The settings app has been added !!!

| image | image |
|-|-|

#53 #100 #302 #303 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by yashash1511** [comment]
@blueedgetechno for now I set a max-width to settings app ig we can make it more responsive for smaller screens later.

**Comment by andrewstech** [comment]
Hey @yashash1511 test-on-pr / test-tauri will fail till after this is merged due to me adding the keyfiles. But don't worry I have manually checked it and it works.

**Review by andrewstech — APPROVED** [review]
Looks ready to merge

**Comment by Posandu** [comment]
@yashash1511 ig this should changed to blue 
image

**Comment by yashash1511** [comment]
@Posandu I was thinking about adding features like user being able to set their own name. So we will switch directly to that .

**Comment by yashash1511** [comment]
@blueedgetechno I didn't remove container query polyfill as i think we have many uses for it.

for example in the calculator app we can have history pane automatically show after certain width just like real win11.

**Comment by blueedgetechno** [comment]
Merge it, 🎉

**Pull request merged**
