### PR TITLE
More features in settings (WIP)

### PR DESCRIPTION
**Pull request by yashash1511**
image
image
image

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by yashash1511** [comment]
# WIP DO NOT MERGE

**Comment by MalikIdreesHasanKhan** [comment]
I have been waiting for this for 7 months.

**Comment by yashash1511** [comment]
> I have been waiting for this for 7 months.

lol windows 11 wasn't even launched back then

**Comment by yashash1511** [comment]
> It wasn't, but there were leaked builds

no I am on windows 11 since the first build was leaked back then in the leaked build it still had the old settings app. the first time we saw the new setting app was on 5 october during win11 launce event

**Pull request merged**
