### PR TITLE
bugfix: drag error

### PR DESCRIPTION
**Pull request by linyuan1105**
# Description

mouseDown on the modal title ,there has no any action

### CODE REVIEW

**Review by yashash1511 — APPROVED** [review]
LGTM

**Comment by yashash1511** [comment]
@linyuan1105 we can merge this once you sign the CLA

**Comment by linyuan1105** [comment]
> @linyuan1105 we can merge this once you sign the CLA

i have signed

**Comment by yashash1511** [comment]
> i have signed

`I have read the CLA Document and I hereby sign the CLA`

@linyuan1105 you have copy paste the above as a comment to sign it.

**Pull request merged**
