### PR TITLE
correct the reaction of click

### PR DESCRIPTION
**Pull request by Gx229**
# Description
the previous edition can't react correctly,such as:  
1. click=> setting,file,store  the next click of setting icon can't open setting panel . It always takes me more than once click to open a app in taskbar
2. click=> setting,file,store  then switch between file and store , and minimize file and store, the setting panel on top but the  status bar shows that it is folded.
3. click the edge of icon , animation shows but click event are muted(because ,after the click , the icon become small，there is no icon in the click position when the mouse is released, so it does not constitute a complete click event

## Type of change

1. rewrite the if-else branch
2. add a div on img to capture the click event

- [√] Bug fix (non-breaking change which fixes an issue)

### ！！！

I tried a variety of scenarios to make sure I didn't add bugs, but I can't guarantee that there are no omissions

### CODE REVIEW

**Comment by MalikIdreesHasanKhan** [comment]
I thought that taking multiple clicks to open was because of my internet lol

**Comment by yashash1511** [comment]
image

noo

**Comment by Gx229** [comment]
> image image
> 
> please don't push the package-lock.json file you downdated it to lockFile version 1 from 2 this might happen automatically due to older node/npm version

got it

**Review by yashash1511 — APPROVED** [review]
lgtm

**Comment by yashash1511** [comment]
@Gx229 we will have to revert this as it causes this bug #343
Can you recreate this without it causing apps installed from the store being rendered twice

**Comment by yashash1511** [comment]
@Gx229 119ffab5032f326b2f4db683c6c276e55625c2fb changes to src/reducers/apps.js file were reverted
as it caused apps installed from the store being rendered twice #343

**Pull request merged**
