### PR TITLE
feat: Opening of corresponding apps upon clicking.

### LINKED ISSUE #802: The icons should open the corresponding app when clicked.
**Is your feature request related to a problem? Please describe.**
In the taskbar, clicking on the up arrow reveals a small window with several icons, but they remain unresponsive when clicked.

**Describe the solution you'd like**
When those icons are clicked then they should open their corresponding apps.

**Describe alternatives you've considered**
No alternative.

**Additional context**
Screenshot 2023-10-04 171332

### PR DESCRIPTION
**Pull request by git-init-priyanshu**
# Description

Screenshot 2023-10-05 161612

When you click on these icons, they open the corresponding apps.
Few Changes: Since the Windows Defender and Microsoft Teams apps do not exist, I've replaced them with Calculator and Notepad.

Fixes #802 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by glitch128** [comment]
I have one suggestion for this. When you click the icon, the menu should collapse.

**Comment by yashash-pugalia** [comment]
> I have one suggestion for this. When you click the icon, the menu should collapse.

Yes @git-init-priyanshu can you do this aswell, after that we can merge this PR.

**Comment by git-init-priyanshu** [comment]
> > I have one suggestion for this. When you click the icon, the menu should collapse.
> 
> Yes @git-init-priyanshu can you do this aswell, after that we can merge this PR.

I have implemented this feature. You can check.

**Comment by yashash-pugalia** [comment]
Thanks for the PR :)

**Pull request merged**
