### PR TITLE
Centered the suspense fallback Loading message

### PR DESCRIPTION
**Pull request by Oussamaosman02**
# Description
I centered the **`Loading...`** message part when the web is loading.I wrapped the `h1` in a `div`. Also i added an id to it and make apropiate **css changes** in index.css to have it centered in the midle of the screen
It isn´t such a relevant thing but it looks better if it is centered and not in the top left 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by Oussamaosman02** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Oussamaosman02** [comment]
recheck

**Review by yashash1511 — COMMENTED** [review]
LGTM

**Comment by Lukas-Batema** [comment]
> LGTM

DLGTM* /jk

**Pull request merged**
