### PR TITLE
terminal color command

### PR DESCRIPTION
**Pull request by matteomessmer**
# Description
Improved the terminal: added color command

Related to #669 (issue)

## Type of change
New feature (non-breaking change which adds functionality)

image

### CODE REVIEW

**Comment by matteomessmer** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by matteomessmer** [comment]
recheck

**Comment by yashash1511** [comment]
noice 👍

**Review by yashash1511 — COMMENTED** [review]
LGTM

**Pull request merged**
