### PR TITLE
make weather widget show user's current weather

### PR DESCRIPTION
**Pull request by waterblock79**
Make weather widget show currect weather of user's city, by using IPAPI.co and OpenWeatherMap.

image

image

### CODE REVIEW

**Comment by waterblock79** [comment]
seems heres a error beacause ip-api.com is not under https... i will fix it

**Comment by waterblock79** [comment]
seems right now
image

**Comment by blueedgetechno** [comment]
I have scrapped like a dozen weather api's only because they were using oauth and have limited calls per month. I the had to sought some randomly genrated weather info. I will keep this pull request in mind in case we find any reliable source.

**Comment by andrewstech** [comment]
I have found a weather api that doesn't require registration and I can't see a calls limit.

http://www.7timer.info/bin/api.pl?lon=113.17&lat=23.09&product=astro&output=xml

http://www.7timer.info/doc.php

**Comment by blueedgetechno** [comment]
@andrewstech Even if there is apparent limit [https://www.7timer.info/doc.php#faq](https://www.7timer.info/doc.php#faq), it is still the best option for now.

**Comment by andrewstech** [comment]
Sorry did not see that section of the site. There website is not very mobile friendly.  Also when the code is on Netlify or github pages its static. Meaning that it's the users browser making api request. Therefore we should be fine.

**Comment by blueedgetechno** [comment]
I'm not sure if the limit is imposed on there sever or will be on our client side. Either way, its a good progess.

**Comment by Lukas-Batema** [comment]
> THIS ISSUE HAS BEEN REPORTED STALE BY ``` Github server AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH  ```

What... the... hell...

**Pull request closed without merging**
