### PR TITLE
Fixed most of the key warnings

### PR DESCRIPTION
**Pull request by Gx229**
# Description

Add some key to fix the warnings for home page and other scenarios

## Type of change

- [√] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by yashash1511** [comment]
Duplicate of #330

**Comment by yashash1511** [comment]
image

donno what am I doing
image

**Comment by blueedgetechno** [comment]
XD

**Comment by Gx229** [comment]
> image
> 
> donno what am I doing image

I initiated a wrong commit earlier, but don't know how to cancel the previous one🤣

**Comment by yashash1511** [comment]
@andrewstech ig closing the PR made close.yml workflow delete the win11bot repo giving this error
image

maybe the repo should be recreated on being reopened

**Pull request closed without merging**
