### PR TITLE
Updated about.js

### PR DESCRIPTION
**Pull request by MalikIdreesHasanKhan**
I apologize for my 2nd pull request in 24 hours but,
Windows 365 is more of a virtual desktop than a cloud pc, as it syncs with your desktop but uses Microsoft hardware

### CODE REVIEW

**Comment by MalikIdreesHasanKhan** [comment]
Sorry about the extra commits.

**Comment by Posandu** [comment]
The old one is good ;)

**Comment by yashash1511** [comment]
> Sorry about the extra commits.

you could always squash & merge them

**Comment by yashash1511** [comment]
> I apologize for my 2nd pull request in 24 hours but, Windows 365 is more of a virtual desktop than a cloud pc, as it syncs with your desktop but uses Microsoft hardware

https://www.microsoft.com/en-in/windows-365 microsoft itself calls it cloud pc

**Comment by MalikIdreesHasanKhan** [comment]
Closing it.Thanks

**Pull request closed without merging**
