### PR TITLE
updated scrollBars to look like win11 :)

### PR DESCRIPTION
**Pull request by yashash1511**
image

image

### CODE REVIEW

**Comment by blueedgetechno** [comment]
This change is breaking,

image

It destroys the aesthetic of few apps. I would rather suggest to keep thos thinScroll and medScroll and manually replace them where the new one fits like store, explorer etc. And keep the rest intact.

**Comment by yashash1511** [comment]
> It destroys the aesthetic of few apps. I would rather suggest to keep those thinScroll and medScroll and manually replace them where the new one fits like store, explorer etc. And keep the rest intact.

okey :)

**Comment by yashash1511** [comment]
@blueedgetechno  fixed now pls review:)

**Comment by MalikIdreesHasanKhan** [comment]
In case anyone wants to know who the character in the photo posted by @blueedgetechno is, it's Pacha, from Disney's 2000 released animated movie  The Emperors New Groove.

**Comment by blueedgetechno** [comment]
even I didn't knew that

**Comment by MalikIdreesHasanKhan** [comment]
@blueedgetechno 🤓

**Pull request merged**
