### PR TITLE
🐛 Fix bugs and added Lazy loading

### PR DESCRIPTION
**Pull request by Posandu**
# Description

Fixed bugs and added Lazy loading component

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by yashash1511** [comment]
hi @Posandu can you list the bugs fixed

**Comment by Posandu** [comment]
The time in the taskbar was not being updated. I fixed it @yashash1511

**Review by yashash1511 — APPROVED** [review]
LGTM

**Comment by yashash1511** [comment]
why locfile v1 @Posandu  please update node js

**Pull request merged**
