### PR TITLE
BrythonRunner Introduced, thanks to sheer will of @andrewstech. "python" command in windows terminal

### PR DESCRIPTION
**Pull request by blueedgetechno**
Type `python` followed by a single line python program in the terminal to test it.
For example `C:/Users/Blue>  python print("Hello World!")`

### CODE REVIEW

**Comment by MalikIdreesHasanKhan** [comment]
Let's Goooooooo!
maxresdefault (1)
Me waiting for win11bot to finish the deploy so I can try the command

**Comment by blueedgetechno** [comment]
> Let's Goooooooo! Me waiting for win11bot to finish the deploy so I can try the command

you can already, visit https://dev.blueedge.me

**Comment by MalikIdreesHasanKhan** [comment]
It works
it works
snape approves

**Comment by blueedgetechno** [comment]
Yup, it works

image

**Pull request merged**
