### PR TITLE
Settings App :)

### PR DESCRIPTION
**Pull request by yashash1511**
# The settings app has been added !!!

| image | image |
|-|-|

#53 #100 #302 #303 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by yashash1511** [comment]
# Do not merge one last thing needs to be fixed

**Comment by MalikIdreesHasanKhan** [comment]
Amazing!

**Comment by blueedgetechno** [comment]
LGTM

**Comment by blueedgetechno** [comment]
image

The side nav is looking shorter, let me add some comments to fix that

**Comment by yashash1511** [comment]
nooooooo why merge there are some bugs

**Comment by Posandu** [comment]
@blueedgetechno wtf

**Comment by blueedgetechno** [comment]
oh sorry, I was misdirectly any andrew's merge-the-pullrequest tag

**Comment by andrewstech** [comment]
> oh sorry, I was misdirected by andrew's mega-pullrequest tag

Hahaha

**Pull request merged**
