### PR TITLE
moving VS-Code to the Store : )

### PR DESCRIPTION
**Pull request by yashash1511**
to be added as an app in the store : )

### CODE REVIEW

**Comment by blueedgetechno** [comment]
no, don't remove it. Change the url to vscode.dev or something else but don't remove it. ;-;

**Comment by yashash1511** [comment]
> no, don't remove it. Change the url to vscode.dev or something else but don't remove it. ;-;

I though I would remove from here and make a PR to add it to store in the win11bot repo

**Comment by blueedgetechno** [comment]
We don't have much interactive app for pinned section and this is one of defaults. I don't think we should remove this.

**Comment by Lukas-Batema** [comment]
> We don't have much interactive app for pinned section and this is one of defaults. I don't think we should remove this.

I don't know that many people programme, that use this project. I think it should be removed and added to the store. The sole reason and proof of/for this is: sites like [GizPie](https://gizpie.com/windows-11-in-react-run-windows-11-browser/), and others bring new users who usually don't know how to code. Just search `win 11 react`, scroll down a bit, and you'll see some reaction videos to the real Win11, which may be what the user intended to search for in the first place, scroll a bit more, if they did miss the videos, then you get the project.

**Comment by MalikIdreesHasanKhan** [comment]
@Lukas-Batema I agree, I found out that this project existed thanks to GizmoPie

**Comment by yashash1511** [comment]
Blue, we are not removing it, we are just moving it from being an preinstalled to an app in the store : )

**Comment by yashash1511** [comment]
we are not exactly removing it, we are just moving it from being an preinstalled to an app in the store : )

**Comment by Lukas-Batema** [comment]
> we are not exactly removing it, we are just moving it from being an preinstalled to an app in the store : )

I realise that, but my points still stand, nonetheless.

**Comment by yashash1511** [comment]
> I realise that, but my points still stand, nonetheless.

My reply was to Blue's comment, I totally agree with your points : )

**Comment by Lukas-Batema** [comment]
> > I realise that, but my points still stand, nonetheless.
> 
> My reply was to Blue's comment, I totally agree with your points : )

Ah, okay.

**Comment by blueedgetechno** [comment]
yes yes I understand, I will merge this pr along with file explorer otherwise it might cause some conflicts with wnapp.scss

**Comment by yashash1511** [comment]
> yes yes I understand, I will merge this pr along with file explorer otherwise it might cause some conflicts with wnapp.scss

okey : )

**Comment by andrewstech** [comment]
Added the not-stale label so git actions won't close this

**Comment by yashash1511** [comment]
> yes yes I understand, I will merge this pr along with file explorer otherwise it might cause some conflicts with wnapp.scss

.

**Pull request merged**
