### PR TITLE
Added ipconfig Command

### PR DESCRIPTION
**Pull request by TechSpiritSS**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
#386 
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

Added support for ipconfig like command
image

### CODE REVIEW

**Comment by TechSpiritSS** [comment]
What's a CLA Document?

got this on clicking link
image

**Comment by TechSpiritSS** [comment]
there might be some extra prettier changes due to different formatting style.

**Comment by andrewstech** [comment]
> What's a CLA Document?
> 
> got this on clicking link image

Sorry the link was updated. https://store.win11react.com/cla/

**Comment by andrewstech** [comment]
> How do I sign this CLA? I have no idea regarding CLA. I am a college student and performing this contribution as a individual

Read the page on the URL I sent before it's an essentially a thing that says you allow us to use your contribution publicly.  Then just send the message here:

 I have read the CLA Document and I hereby sign the CLA. .

It's case sensitive. Once done the check will automatically pass

**Comment by TechSpiritSS** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by andrewstech** [comment]
recheck

**Pull request merged**
