### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by inwinter04**
# Description
Link to a Chinese language version
链接一个中文语言版本

## Type of change
- [x] This change requires a documentation update

### CODE REVIEW

**Comment by yashash-pugalia** [comment]
Hey @inwinter04 I think if we could have the chinese readme as README_CN.md or something like that in this repo only that would be better way.

**Comment by inwinter04** [comment]
> Hey @inwinter04 I think if we could have the chinese readme as README_CN.md or something like that in this repo only that would be better way.

Yes, I think that's pretty good. I'll upload a copy of README_CN.md to repo later. 😎
But there is no denying that there is a lot of English in the project, and I translated it completely in another repo. This is how a translated repo is linked.

**Comment by yashash-pugalia** [comment]
I see, earlier i though it was just a link to the chinese readme now i see you redid the whole project in chinese.

**Comment by yashash-pugalia** [comment]
@blueedgetechno we need your thoughts on this.

**Comment by blueedgetechno** [comment]
But it works fine, then merge it I guess.

**Comment by inwinter04** [comment]
> But it works fine, then merge it I guess.

You can use the link https://win11.iamdt.eu.org/ access to Chinese Demo project.

**Comment by yashash-pugalia** [comment]
Hey @inwinter04, we are happy that you liked it enough to play and create your own version with chinese translation.

One thing we noticed is that the hosted version has the name of the orignal creator "Blue Edge" replaced with your name and that in places you are redirecting users to your own site like in the start menu.

image
(redirected to your site)

**Comment by inwinter04** [comment]
> Hey @inwinter04, we are happy that you liked it enough to play and create your own version with chinese translation.
> 
> One thing we noticed is that the hosted version has the name of the orignal creator "Blue Edge" replaced with your name and that in places you are redirecting users to your own site like in the start menu.
> 
> image
> (redirected to your site)

I'll point the link to Blue Edge the day after tomorrow. Thanks for the reminder.

**Comment by yashash-pugalia** [comment]
Once the required changes are done we can have this merged, and sorry for the delay :)

**Comment by inwinter04** [comment]
> Once the required changes are done we can have this merged, and sorry for the delay :)

There's nothing wrong with that.（＾ｖ＾） 
It is an honor to be able to contribute here.

**Comment by inwinter04** [comment]
> Once the required changes are done we can have this merged, and sorry for the delay :)

Thank you for waiting. I have finished the changes. Request merge.

**Comment by andrewstech** [comment]
Thank you!

**Pull request merged**
