### PR TITLE
Store banner change

### PR DESCRIPTION
**Pull request by RedEdge967**
# Description

Changed the Luca banner to No way home poster in store. does this work? this relevant to #357 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by RedEdge967** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by RedEdge967** [comment]
recheck

**Comment by Posandu** [comment]
Why? This is useless TBH

**Comment by RedEdge967** [comment]
but plz merge brother

**Comment by andrewstech** [comment]
Bruhh

**Comment by Lukas-Batema** [comment]
Bruhhh

**Comment by Lukas-Batema** [comment]
Reverting due to incorrect margin and padding in image

**Comment by Lukas-Batema** [comment]
> do you know how to fix it?

Use a correctly sized image, and no, I cannot edit the image dimensions, as it would stretch the image, and I am on mobile.

**Comment by RedEdge967** [comment]
okay @Lukas-Batema I will open a new PR after I found a image

**Comment by Lukas-Batema** [comment]
Why does this need to be changed, xD?

**Comment by RedEdge967** [comment]
Okay I won't open a new PR

**Comment by Posandu** [comment]
https://github.com/blueedgetechno/win11React/pull/358#issuecomment-1079178025 I said this before

**Pull request merged**
